Website = "https://github.com/tejashwikalptaru/gotune"

[Details]
Icon = "icon.png"
Name = "Go Tune"
ID = "com.gotune.app"
Version = "0.0.1"
Build = 13

[LinuxAndBSD]
GenericName = "Music Player"
Categories = ["Audio", "Music", "Player", "AudioVideo"]
Comment = "A lightweight music player built with Go and Fyne"
Keywords = ["music", "audio", "player", "mp3", "flac"]
